version: '3.8'
services:
  devcontainer:
    build:
      dockerfile: Dockerfile
      context: .
      target: devcontainer
    environment:
      CR_HOST: $CR_HOST
      HOST_IP: $HOST_IP
      POSTGRES_DATABASE: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/home/vscode/.ssh:cached
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-data:
  tmp:
