version: '3.8'
services:
  devcontainer:
    build:
      dockerfile: Dockerfile
      context: .
      target: devcontainer
    environment:
      CR_HOST: $CR_HOST
      HOST_IP: $HOST_IP
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/home/vscode/.ssh:cached
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  postgres-data:
  tmp:
