version: '3.8'
services:
  devcontainer:
    build:
      dockerfile: mcr.microsoft.com/devcontainers/base:jammy
      context: .
      target: devcontainer
    # network_mode: service:spanner-emulator
    environment:
      CR_HOST: $CR_HOST
      HOST_IP: $HOST_IP
    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh:/home/vscode/.ssh:cached
volumes:
  tmp:
